### PR TITLE
Use normalized paths throughout

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by grawk** [comment]
Looks good :+1:

**Comment by aredridel** [comment]
There. Test suite passed in windows with the (as yet unreleased) fix for `dust.compile` and `\` in template names.

**Comment by aredridel** [comment]
@ppnsanders this one's for you.

**Comment by aredridel** [comment]
So: Is the change in cache key format a breaking change?

**Comment by grawk** [comment]
It's only breaking if the cacheKey is used anywhere outside of `bundalo`. I don't _think_ it is..

**Comment by aredridel** [comment]
I see no evidence of that publicly or privately.

**Pull request merged**
